### ISSUE TITLE
Linker error when compiling on Windows with Visual Studio 17

### ISSUE THREAD

**Issue by zzxoto** [ndm767/glGraph#1]
Seems SDL2 defines `main` as well, and the `main` defined in `main.cpp` conflicts with the SDL2's definition. I fixed it by `#define SDL_MAIN_HANDLED` in the first line of the `main.cpp`

**Comment by ndm767** [comment]
I believe that should work. I don't have a lot of experience writing C++ for Windows so if you have any more issues, please tell me!
